##################################################################################################
# Echo Frontend
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
spec:
  ports:
  - port: 8080
    name: http
  - port: 9080
    name: http2-grpc
  selector:
    app: frontend
    version: v1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  labels:
    account: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v1
  labels:
    app: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      serviceAccountName: frontend
      containers:
      - name: frontend
        image: ghcr.io/nmnellis/istio-echo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        args:
          - --name
          - frontend-v1
          - --port
          - "8080"
          - grpc
          - "9080"
          - --version
          - v1
          - --cluster
          - cluster-1
---
##################################################################################################
# Echo Backend V1/V2
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    service: backend
spec:
  ports:
  - port: 8080
    name: http
  - port: 9080
    name: http2-grpc
  selector:
    app: backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  labels:
    account: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1
  labels:
    app: backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      serviceAccountName: backend
      containers:
      - name: backend
        image: ghcr.io/nmnellis/istio-echo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        args:
          - --name
          - backend-v1
          - --port
          - "8080"
          - --grpc
          - "9080"
          - --version
          - v1
          - --cluster
          - cluster-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
  labels:
    app: backend
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v2
  template:
    metadata:
      labels:
        app: backend
        version: v2
    spec:
      serviceAccountName: backend
      containers:
      - name: backend
        image: ghcr.io/nmnellis/istio-echo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        args:
          - --name
          - backend-v2
          - --port
          - "8080"
          - --grpc
          - "9080"
          - --version
          - v1
          - --cluster
          - cluster-1
---